#!/usr/bin/env bash
# Writes the ABIs the services and app need into packages/contracts as typed
# TypeScript (`as const`, so viem infers every argument and return type).
# CI reruns this and fails if the committed copy differs.
set -euo pipefail

cd "$(dirname "$0")/.."
out=../packages/contracts/src/abi
mkdir -p "$out"

export_abi() {
  local contract=$1 name=$2
  {
    echo "// Generated by contracts/script/export-abi.sh from ${contract}. Do not edit."
    printf 'export const %s = %s as const;\n' "$name" "$(forge inspect "$contract" abi --json)"
  } >"$out/$contract.ts"
}

export_abi MatoCreditLine matoCreditLineAbi
export_abi TestAUSD testAusdAbi
export_abi MockEarnAUSD mockEarnAusdAbi
